keys:
  - &personal_admin  age13vyme78jmvjv499t7dzl2ju4epy90792nje0mvyh6ar93zae75kqyzsr2j
  - &pc age146xlkyvdxgjqjt3fnawtvqgzuk0fwgjsj9gf3c0z3q5n02r49vgsz3nk4s
  - &laptop age1sjlg4s9jq2qlevlkhylguul7ztxr6cassnj7xle7patzlgmy5syqan5vpz

creation_rules:
  - path_regex: secrets/personal\.yaml$
    key_groups:
      - age:
          - *personal_admin
          - *pc
          - *laptop
