name: Linter
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Apply linters
        run: |
          nix run nixpkgs#statix -- fix .
          nix run nixpkgs#deadnix -- --edit .
          nix fmt .

      - uses: peter-evans/create-pull-request@v7
        id: linter-pr
        with:
          branch: bot/nix-linter
          commit-message: "chore(linter): Running nix fmt, deadnix, statix"
          title: "chore(linter): Cleaning and linting nix files"
          delete-branch: true

      - name: Enable auto-merge
        if: steps.update.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh pr merge --auto --squash "${{ steps.linter-pr.outputs.pull-request-number }}"

