name: Linter
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Apply linters
        run: |
          nix run nixpkgs#statix -- fix .
          nix run nixpkgs#deadnix -- --edit .
          nix fmt .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(linting): Running fmt, deadnix, statix"
