name: Test

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      
      - name: Test
        run: nix build .#nixosConfigurations.gpd.config.system.build.toplevel --dry-run
